apiVersion: v1
kind: Service
metadata:
  name: realty-api-svc
  namespace: api
spec:
  selector:
    app: realty-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort