# ── Executor ──────────────────────────────────────────────────────────────────
executor: LocalExecutor

# ── Imagen oficial de Airflow 3.2.0 ──────────────────────────────────────────
# Sin personalización — usamos la oficial directamente
images:
  airflow:
    repository: juannavas38/realty-airflow   # TODO: confirmar usuario DockerHub
    tag: "latest"
    pullPolicy: IfNotPresent

# ── Paquetes adicionales ──────────────────────────────────────────────────────
extraPipPackages:
  - "apache-airflow-providers-postgres"
  - "psycopg2-binary"
  - "mlflow"
  - "scikit-learn"
  - "xgboost"
  - "pandas"
  - "numpy"

# ── Base de datos externa ─────────────────────────────────────────────────────
data:
  metadataConnection:
    user: mlops
    pass: mlops2026
    host: postgres-svc.mlops.svc.cluster.local
    port: 5432
    db: airflow_metadata
    protocol: postgresql

# ── Deshabilitar componentes incluidos en el chart ────────────────────────────
postgresql:
  enabled: false

redis:
  enabled: false

# ── Webserver ─────────────────────────────────────────────────────────────────
webserver:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# ── Scheduler ─────────────────────────────────────────────────────────────────
scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 3Gi

# ── DAGs ──────────────────────────────────────────────────────────────────────
dags:
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi
    accessMode: ReadWriteOnce

# ── Logs ──────────────────────────────────────────────────────────────────────
logs:
  persistence:
    enabled: false

# ── Variables de entorno ──────────────────────────────────────────────────────
env:
  - name: MLFLOW_TRACKING_URI
    value: "http://mlflow-svc.mlops.svc.cluster.local:5000"
  - name: MLFLOW_S3_ENDPOINT_URL
    value: "http://minio-svc.mlops.svc.cluster.local:9000"
  - name: AWS_ACCESS_KEY_ID
    value: "minioadmin"
  - name: AWS_SECRET_ACCESS_KEY
    value: "minioadmin2026"

# ── Seguridad ─────────────────────────────────────────────────────────────────
webserverSecretKey: "mlops2026javeriana"
defaultAirflowUsername: admin
defaultAirflowPassword: admin2026

# ── Configuración Airflow ─────────────────────────────────────────────────────
config:
  core:
    load_examples: "false"
    dags_are_paused_at_creation: "false"
  scheduler:
    dag_dir_list_interval: "30"