# ── Executor ──────────────────────────────────────────────────────────────────
executor: LocalExecutor

# ── Imagen personalizada con dependencias ML ──────────────────────────────────
images:
  airflow:
    repository: masterofelectronic/airflow-mlops
    tag: "3.2.0"
    pullPolicy: IfNotPresent

# ── Base de datos externa (PostgreSQL en namespace mlops) ─────────────────────
data:
  metadataConnection:
    user: mlops
    pass: mlops2026
    host: postgres-svc.mlops.svc.cluster.local
    port: 5432
    db: airflow_metadata
    protocol: postgresql

# ── Deshabilitar PostgreSQL y Redis incluidos en el chart ─────────────────────
postgresql:
  enabled: false

redis:
  enabled: false

# ── Webserver ─────────────────────────────────────────────────────────────────
webserver:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# ── Scheduler ─────────────────────────────────────────────────────────────────
scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 3Gi

# ── DAGs — PVC local ──────────────────────────────────────────────────────────
dags:
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi
    accessMode: ReadWriteOnce

# ── Logs — sin persistencia ───────────────────────────────────────────────────
logs:
  persistence:
    enabled: false

# ── Variables de entorno globales ─────────────────────────────────────────────
env:
  - name: MLFLOW_TRACKING_URI
    value: "http://mlflow-svc.mlops.svc.cluster.local:5000"
  - name: MLFLOW_S3_ENDPOINT_URL
    value: "http://minio-svc.mlops.svc.cluster.local:9000"
  - name: AWS_ACCESS_KEY_ID
    value: "minioadmin"
  - name: AWS_SECRET_ACCESS_KEY
    value: "minioadmin2026"

# ── Seguridad ─────────────────────────────────────────────────────────────────
webserverSecretKey: "mlops2026javeriana"
defaultAirflowUsername: admin
defaultAirflowPassword: admin2026

# ── Configuración Airflow ─────────────────────────────────────────────────────
config:
  core:
    load_examples: "false"
    dags_are_paused_at_creation: "false"
  scheduler:
    dag_dir_list_interval: "30"