apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: masterofelectronic/airflow-mlops:2.9.1
          command: ["airflow", "scheduler"]
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: mlops-secrets
                  key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: mlops-secrets
                  key: AIRFLOW__CORE__FERNET_KEY
          envFrom:
            - configMapRef:
                name: airflow-config
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1500m"
              memory: "2Gi"
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: logs
              mountPath: /opt/airflow/logs
          livenessProbe:
            exec:
              command:
                - airflow
                - jobs
                - check
                - --job-type
                - SchedulerJob
                - --hostname
                - $(hostname)
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc