apiVersion: v1
kind: Service
metadata:
  name: realty-ui-svc
  namespace: streamlit
spec:
  selector:
    app: realty-ui
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30801
  type: NodePort